# Generated by Django 5.0.3 on 2024-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todo_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
